# Arcana Card Upload - Direct Cloudinary API (no backend required)
# Upload all 40 SVG cards directly to Cloudinary using unsigned upload preset
# Usage: .\upload-cards-direct.ps1

param(
    [string]$CloudName = "ssoic87m",
    [string]$UploadPreset = "arcana_deck_assets"
)

$ErrorActionPreference = "Stop"
$CardsPath = "d:/gmae/frontend/src/assets/cards/default/cards"
$Folder = "basic exploding kittens"
$UploadUrl = "https://api.cloudinary.com/v1_1/$CloudName/image/upload"

Write-Host "========================================" -ForegroundColor Cyan
Write-Host " Arcana Card Upload -> Cloudinary" -ForegroundColor Cyan
Write-Host " Cloud: $CloudName | Preset: $UploadPreset" -ForegroundColor Gray
Write-Host " Folder: $Folder" -ForegroundColor Gray
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Helper function to upload via curl.exe (multipart form with -F works reliably)
function Upload-CardFile {
    param(
        [string]$FilePath,
        [string]$FileName
    )

    $curlOut = [System.IO.Path]::GetTempFileName()
    $curlErr = [System.IO.Path]::GetTempFileName()

    & curl.exe -s -X POST "$UploadUrl" `
        -F "file=@$FilePath" `
        -F "upload_preset=$UploadPreset" `
        -F "folder=$Folder" `
        -F "tags=basic-exploding-kittens,card" `
        -o $curlOut `
        --stderr $curlErr

    $body = if (Test-Path $curlOut) { Get-Content $curlOut -Raw } else { "" }
    Remove-Item $curlOut, $curlErr -Force -ErrorAction SilentlyContinue

    if ([string]::IsNullOrWhiteSpace($body)) {
        return @{ Success = $false; Error = "empty response" }
    }

    try {
        $json = $body | ConvertFrom-Json
        if ($json.secure_url) {
            return @{ Success = $true; Data = $json }
        }
        return @{ Success = $false; Error = $json.error.message }
    }
    catch {
        return @{ Success = $false; Error = "parse: $($_.Exception.Message)" }
    }
}

# Step 1: Verify preset exists first
Write-Host "[1/3] Verifying upload preset '$UploadPreset'..." -NoNewline

$verifyResult = Upload-CardFile -FilePath "$CardsPath/bomb-1.svg" -FileName "bomb-1.svg"

if ($verifyResult.Success) {
    Write-Host " OK" -ForegroundColor Green
    Write-Host "   Uploaded: $($verifyResult.Data.original_filename)" -ForegroundColor Gray
    Write-Host "   URL: $($verifyResult.Data.secure_url)" -ForegroundColor Gray
} else {
    Write-Host " FAILED" -ForegroundColor Red
    Write-Host "   Error: $($verifyResult.Error)" -ForegroundColor Red
    Write-Host ""
    Write-Host "NOTE: Make sure upload preset '$UploadPreset' exists with signing mode 'Unsigned'." -ForegroundColor Yellow
    exit 1
}

# Step 2: Count files
$files = Get-ChildItem "$CardsPath/*.svg" | Sort-Object Name
$total = $files.Count
Write-Host "[2/3] Found $total SVG files" -ForegroundColor White
Write-Host ""

# Step 3: Upload all
Write-Host "[3/3] Uploading all cards..." -ForegroundColor Yellow
Write-Host ""

$success = 0
$failed = 0
$results = @()

foreach ($file in $files) {
    $fileName = $file.Name
    Write-Host "  $fileName..." -NoNewline

    $uploadResult = Upload-CardFile -FilePath $file.FullName -FileName $fileName

    if ($uploadResult.Success) {
        $json = $uploadResult.Data
        Write-Host " OK ($($json.secure_url))" -ForegroundColor Green
        $results += [PSCustomObject]@{
            FileName = $fileName
            PublicId = $json.public_id
            Url      = $json.secure_url
            Width    = $json.width
            Height   = $json.height
            Status   = "OK"
        }
        $success++
    } else {
        Write-Host " FAILED: $($uploadResult.Error)" -ForegroundColor Red
        $results += [PSCustomObject]@{
            FileName = $fileName
            PublicId = ""
            Url      = ""
            Width    = 0
            Height   = 0
            Status   = "FAILED: $($uploadResult.Error)"
        }
        $failed++
    }
}

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Result: $success OK | $failed failed" -ForegroundColor $(if ($failed -eq 0) { "Green" } else { "Yellow" })
Write-Host "========================================" -ForegroundColor Cyan

# Save results
$outFile = "d:/gmae/card-upload-results.json"
$results | ConvertTo-Json -Depth 5 | Out-File -FilePath $outFile -Encoding UTF8
Write-Host "Results: $outFile" -ForegroundColor Gray

# Generate cardCloudinary.js
if ($success -gt 0) {
    $urlMap = @{}
    foreach ($r in $results) {
        if ($r.Status -eq "OK") {
            $cardId = $r.FileName -replace '\.svg$', ''
            $urlMap[$cardId] = $r.Url
        }
    }

    $jsContent = @"
// Auto-generated by upload-cards-direct.ps1
// DO NOT EDIT MANUALLY

const CARD_CLOUDINARY = {
  baseUrl: "https://res.cloudinary.com/$CloudName/image/upload",
  cards: $(($urlMap | ConvertTo-Json -Depth 5 -Compress)),
};

export { CARD_CLOUDINARY };
"@
    $jsContent | Out-File -FilePath "d:/gmae/frontend/src/games/exploding-cats/cardCloudinary.js" -Encoding UTF8
    Write-Host "Updated: frontend/src/games/exploding-cats/cardCloudinary.js" -ForegroundColor Green
}