<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
    <PackageReference Include="CloudinaryDotNet" Version="1.26.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Arcana.Infrastructure\Arcana.Infrastructure.csproj" />
    <ProjectReference Include="..\Arcana.Application\Arcana.Application.csproj" />
    <ProjectReference Include="..\Arcana.Shared\Arcana.Shared.csproj" />
  </ItemGroup>

</Project>
